@startuml

skinparam classAttributeIconSize 0
skinparam wrapWidth 400

class TextFormat {
	.. INSTANCE VARIABLES ..
	-fontFamily : FontFamily
	-hasSerif : boolean
	-fontWeight : FontWeight
	-isItalicized : boolean
	-isUnderlined : boolean
	-isCondensed : boolean
	-elementColor : ElementColor
	.. DEFAULT VALUES ..
	{static} -DEFAULT_FONT_FAMILY : FontFamily = FontFamily.LATIN
	{static} -DEFAULT_HAS_SERIF : boolean = false
	{static} -DEFAULT_FONT_WEIGHT : FontWeight = FontWeight.NORMAL
	{static} -DEFAULT_IS_ITALICIZED : boolean = false
	{static} -DEFAULT_IS_UNDERLINED : boolean = false
	{static} -DEFAULT_IS_CONDENSED : boolean = false
	{static} -DEFAULT_ELEMENT_COLOR : ElementColor = ElementColor.DEFAULT
	== CONSTRUCTOR ==
	-TextFormat(fontFamily : FontFamily, hasSerif : boolean, fontWeight : FontWeight, isItalicized : boolean, isUnderlined : boolean, isCondensed : boolean, elementColor : ElementColor)
	.. CHECK METHODS ..
	-checkArguments(fontFamily : FontFamily, hasSerif : boolean, fontWeight : FontWeight, isItalicized : boolean, isUnderlined : boolean, isCondensed : boolean, elementColor : ElementColor) : void
	-checkNonNull(fontFamily : FontFamily, fontWeight : FontWeight, elementColor : ElementColor) : void
	-checkFont(fontFamily : FontFamily, hasSerif : boolean, fontWeight : FontWeight, isItalicized : boolean, isCondensed : boolean) : void
	.. VALIDATORS ..
	+isValidHasSerif(hasSerif : boolean) : boolean
	+isValidFontWeight(fontWeight : FontWeight) : boolean
	+isValidIsItalicized(isItalicized : boolean) : boolean
	+isValidIsCondensed(isCondensed : boolean) : boolean
	-isValidHasSerif(fontFamily : FontFamily, hasSerif : boolean) : boolean
	-isValidFontWeight(fontFamily : FontWeight, hasSerif : boolean, fontWeight : FontWeight) : boolean
	-isValidIsItalicized(fontFamily : FontFamily, isItalicized : boolean) : boolean
	-isValidIsCondensed(fontFamily : FontFamily, isCondensed : boolean) : boolean
	.. ACCESSORS ..
	+getFontFamily() : FontFamily
	+hasSerif() : boolean
	+getFontWeight() : FontWeight
	+isItalicized() : boolean
	+isUnderlined() : boolean
	+isCondensed() : boolean
	+getElementColor() : ElementColor
	{static} +getDefaultFontFamily() : FontFamily
	{static} +hasSerifByDefault() : boolean
	{static} +getDefaultFontWeight() : FontWeight
	{static} +isItalicizedByDefault() : boolean
	{static} +isUnderlinedByDefault() : boolean
	{static} +isCondensedByDefault() : boolean
	{static} +getDefaultElementColor() : ElementColor
	.. COPY METHODS ..
	+withFontFamily(newFontFamily : FontFamily) : TextFormat
	+withHasSerif(newHasSerif : boolean) : TextFormat
	+withFontWeight(newFontWeight : FontWeight) : TextFormat
	+withIsItalicized(newIsItalicized : boolean) : TextFormat
	+withIsUnderlined(newIsUnderlined : boolean) : TextFormat
	+withIsCondensed(newIsCondensed : boolean) : TextFormat
	+withElementColor(newElementColor : ElementColor) : TextFormat
	.. NEW METHODS ..
	-newHasSerif(newFontFamily : FontFamily) : boolean
	-newFontWeight(newFontFamily : FontFamily, newHasSerif : boolean) : FontWeight
	-newIsItalicized(newFontFamily : FontFamily) : boolean
	-newIsCondensed(newFontFamily : FontFamily) : boolean
	.. VALID METHODS ..
	+validHasSerifSet() : HashSet<Boolean>
	+validFontWeightSet() : HashSet<FontWeight>
	+validIsItalicizedSet() : HashSet<Boolean>
	+validIsCondensedSet() : HashSet<Boolean>
	.. OVERRIDDEN METHODS ..
	+toString() : String
	+equals(o : Object) : boolean
	+hashCode() : int
}

enum FontFamily {

}

enum FontWeight {

}

enum ElementColor {

}

@enduml