@startuml

skinparam classAttributeIconSize 0
skinparam wrapWidth 400

class DividerElement

class AbstractElement
interface ParentElement

enum IndentType

AbstractElement <|-- DividerElement
ParentElement <|.. DividerElement
DividerElement <-- "indentType\n1..1" IndentType


@enduml