@startuml

skinparam classAttributeIconSize 0
skinparam wrapWidth 200

class Card {
	-noteId : int
	-index : int
}
class CardSchedule

Card *-- "schedule\n1..1" CardSchedule

note right of Card
<i>noteId</i> to retrieve the <i>Note</i> this Card is associated with.
<i>index</i> to retrieve the <i>CardType</i> from the <i>Note</i>'s <i>NoteType</i>.
end note

@enduml